DEBUG: null
network:
  task: cyclegan
  G type: ConvCM
  D type: Conv4
  min channels: 8
  dropout: 0.2
  activation type: swish
loss settings:
  adversarial loss type: WGAN
data loading:
  dataset: horse2zebra
  initial sample points: 512
  image shape:
  - 256
  - 256
optimizer:
  G learning rate: 1e-3
  D learning rate: 1e-3
  max steps: 10000
