DEBUG: null
parent: depth
network:
  type: ConvCM
  min channels: 8
  dropout: 0.2
  activation: tanh
  parameterization: polynomial
  final activation: null
optimizer:
  learning rate: 1e-2
  max steps: 10000
