DEBUG: null
parent: depth
network:
  type: SimpleI2I
  min channels: 8
  dropout: 0.1
  activation: tanh
  parameterization: polynomials
  final activation: null
optimizer:
  learning rate: 1e-2
  max steps: 10000
