random seed: 0
paths:
  slurm output dir: ~/code/inrnet/results
  temp dir: ~/code/inrnet/temp
network:
  frozen: false
  conv:
    scale2: 30
    mid_ch:
    - 64
    - 32
optimizer:
  type: AdamW
  weight decay: 1e-3
