network:
  type: ConvCmConv
  task: depth
  min channels: 16
  radius: .15
  steerable: True
  dropout: 0.
data loading:
  dataset: kitti
  image shape:
  - 352
  - 1216
  depth scale: 75.
optimizer:
  learning rate: 1e-4
  max steps: 10000
