network:
  type: FPN
  task: depth
  min channels: 8
  dropout: .2
  parameterization: zernike
data loading:
  dataset: kitti
  image shape:
  - 352
  - 1216
  depth scale: 75.
optimizer:
  learning rate: 1e-3
  max steps: 15000
