network:
  task: generate
  type: inr-wgan
  pretrained: true
  frozen: true
data loading:
  batch size: 4
  subset: train
  dataset: flowers
  sample type: grid
  sample points: 1024
  image shape:
  - 32
  - 32
optimizer:
  type: AdamW
  learning rate: 1e-4
  max steps: 8000
#N=? / bsz * 10 epochs