network:
  task: generate
  type: inr-wgan
  pretrained: false
  frozen: false
data loading:
  batch size: 32
  subset: train
  dataset: fmnist
  sample type: grid
  initial sample points: 49
  initial grid shape:
  - 7
  - 7
  sample points: 784
  image shape:
  - 28
  - 28
optimizer:
  type: AdamW
  learning rate: 1e-3
  max steps: 40000
loss settings:
  adversarial loss type: WGAN
#N=? / bsz * 10 epochs