parent: classify
network:
  type: inr-effnet-s3
data loading:
  N: 1000
  augment: true
  batch size: 192
  subset: train
  dataset: inet12
  input channels: 3
  classes: 12
  sample points: 1024
  sample type: rqmc
  image shape:
  - 64
  - 64
optimizer:
  learning_rate: 1e-3
  max steps: 3000
#N=9600 / bsz * 40 epochs