network:
  task: segment
  type: inr-convnext
  pretrained: true
data loading:
  batch size: 5
  subset: train
  dataset: cityscapes
  classes: 7
  sample points: 8192
  image shape:
  - 64
  - 128
optimizer:
  type: AdamW
  learning rate: 1e-4
  max steps: 5950
#N=2975 / bsz * 10 epochs