network:
  task: segment
  type: inr-convnext
  pretrained: true
  frozen: false
data loading:
  batch size: 1
  subset: train
  dataset: cityscapes
  classes: 7
  sample type: valid
  sample points: 4608
  image shape:
  - 48
  - 96
optimizer:
  type: AdamW
  learning rate: 1e-3
  max steps: 59500
#N=2975 / bsz * 10 epochs
