network:
  task: segment
  type: inr-convnext
  pretrained: true
  frozen: false
data loading:
  seg type: fine
  batch size: 32
  subset: train
  dataset: cityscapes
  classes: 7
  sample type: grid
  sample points: 8192
  image shape:
  - 64
  - 128
optimizer:
  type: AdamW
  learning rate: 1e-3
  max steps: 10000
#N=2975 / bsz * 10 epochs
