parent: seg_train
network:
  type: inr-convnext
data loading:
  seg type: fine
  batch size: 1
  sample type: grid
  image shape:
  - 32
  - 64
optimizer:
  type: AdamW
  learning rate: 1e-3
  max steps: 1000