network:
  type: UNet
  task: depth
  min channels: 8
  dropout: 0.2
  activation type: swish
  parameterization: mlp
data loading:
  dataset: kitti
  image shape:
  - 352
  - 1216
  depth scale: 75.
optimizer:
  learning rate: 1e-4
  max steps: 10000
