parent: classify
network:
  type: inr-2
data loading:
  batch size: 4
  subset: train
  dataset: inet12
  classes: 12
  classes: 12
  sample points: 4096
  image shape:
  - 16
  - 16
  - 16
optimizer:
  learning rate: 1e-2
  max steps: 1000
#N=9600 / bsz * 40 epochs